on:
  push:
    branches:
      - main # Prepare new release on new changes to main

permissions:
  contents: write
  pull-requests: write

name: Prepare new release

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_REPO_TOKEN }}
